sudo: false

language: java

env:
  global:
    - PROTOBUF_VERSION=3.0.0-beta-2
    - OPENSSL_VERSION=1.0.2d
    - LDFLAGS=-L/tmp/protobuf-${PROTOBUF_VERSION}/lib
    - CXXFLAGS=-I/tmp/protobuf-${PROTOBUF_VERSION}/include
    - LD_LIBRARY_PATH=/tmp/protobuf-${PROTOBUF_VERSION}/lib:/tmp/openssl-${OPENSSL_VERSION}/lib

before_install:
    # Work around https://github.com/travis-ci/travis-ci/issues/2317
  - if \[ "$TRAVIS_OS_NAME" = linux \]; then jdk_switcher use oraclejdk8; fi
  - if \[ "$TRAVIS_OS_NAME" = osx \]; then brew update; fi
  - buildscripts/make_dependencies.sh # build protoc into /tmp/protobuf-${PROTOBUF_VERSION}
  - mkdir -p $HOME/.gradle
  - echo "checkstyle.ignoreFailures=false" >> $HOME/.gradle/gradle.properties

install:
  - ./gradlew assemble generateTestProto

before_script:
  - test -z "$(git status --porcelain)" || (git status && echo Error Working directory is not clean. Forget to commit generated files? && false)

after_success:
  - if \[ "$TRAVIS_OS_NAME" = linux \]; then ./gradlew :grpc-all:coveralls; fi

os:
  - linux
  - osx

# This image comes with jdk8
osx_image: xcode7

notifications:
  email: false

# Caching does not work for public repositories with OS X:
# https://github.com/travis-ci/travis-ci/issues/4011
cache:
  directories:
    - /tmp/protobuf-${PROTOBUF_VERSION}
    - /tmp/openssl-${OPENSSL_VERSION}
    - $HOME/.m2/repository/io/netty
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper

before_cache:
  - rm $HOME/.gradle/caches/modules-2/modules-2.lock
  - find $HOME/.gradle/wrapper -not -name "*-all.zip" -and -not -name "*-bin.zip" -delete
